import { createHash } from "node:crypto";
import { revalidatePath, revalidateTag } from "next/cache";
import { getCmsItems, saveCmsItem, withCmsAdvisoryLock } from "@/lib/cmsStore";
import { queueSitemapRefresh } from "@/lib/sitemapHooks";
import { discoverNewsCandidates } from "@/lib/newsDiscovery";
import { composeNewsArticle } from "@/lib/newsGeneration";
import { DEFAULT_NEWS_SITE_ID, getNewsSiteConfig, validateNewsSiteConfig } from "@/lib/newsSiteConfig.mjs";

const RECENT_WINDOW = 180 * 86400000;
const blockedPublicTerms = /SEO Meta|Primary Keyword|Search Intent|AI Citation Ready|CMS checklist|internal linking suggestions|generated by AI/i;
const blockedSalesTerms = /solicitar cotizacion|cotizar ahora|whatsapp|contactenos|precio|MOQ|stock local/i;

function lockName(siteId, task) {
  return `news:${task}:${siteId}`;
}

function dateValue(value) {
  const time = new Date(value || 0).getTime();
  return Number.isFinite(time) ? time : 0;
}

function words(value = "") {
  return String(value).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").match(/[a-z0-9]{3,}/g) || [];
}

function similarity(a, b) {
  const left = new Set(words(a));
  const right = new Set(words(b));
  if (!left.size || !right.size) return 0;
  let common = 0;
  for (const token of left) if (right.has(token)) common += 1;
  return common / (left.size + right.size - common);
}

function maxDuplicationScore(candidate, recentArticles) {
  return Math.max(0, ...recentArticles.map((article) => Math.max(
    similarity(candidate.title, article.title),
    similarity(candidate.summary, article.summary),
    similarity(candidate.body, article.body)
  )));
}

function revalidatePublishedNews(site, slug) {
  for (const locale of ["es-cl", "es", "pt-br", "en"]) {
    revalidatePath(`/${locale}/news`);
    revalidatePath(`/${locale}/news/${slug}`);
  }
  revalidatePath(site.news.sitemapRoute);
  revalidatePath("/sitemap.xml");
  revalidateTag("public-news", { expire: 0 });
}

async function loadState(siteId) {
  const [candidates, allNews] = await Promise.all([
    getCmsItems("news-candidate", { includeInactive: true, siteId }),
    getCmsItems("news", { includeInactive: true, siteId })
  ]);
  const published = allNews.filter((item) => item.status === "published");
  return {
    candidates,
    published,
    recent: published.filter((item) => Date.now() - dateValue(item.publishedAt || item.createdAt) < RECENT_WINDOW)
  };
}

function diagnostics(candidate, extra = {}) {
  return {
    selected_source: candidate?.selectedSource || candidate?.sourceUrl || "",
    rejected_sources: candidate?.rejectedSources || [],
    duplication_score: candidate?.duplicationScore ?? null,
    topic_cluster_id: candidate?.topicClusterId || null,
    information_gain_score: candidate?.informationGainScore ?? null,
    source_groups: candidate?.selectedSourceGroups || [],
    ...extra
  };
}

export function evaluateNewsArticle(article, recentArticles = [], site = null) {
  const failures = [];
  const source = article?.sources?.[0];
  const wordCount = words(article?.body).length;
  const duplicateScore = maxDuplicationScore(article, recentArticles);
  if (!site) failures.push("unknown_site");
  if (!article?.siteId || article.siteId !== site?.siteId) failures.push("site_id_mismatch");
  if (!source?.url || !source?.publishedAt || !source?.sourceName || !source?.supportedFact) failures.push("incomplete_source_evidence");
  if (!article?.title || !article?.summary || !article?.body) failures.push("incomplete_article");
  if (wordCount < site?.news?.desiredWordCount?.min || wordCount > site?.news?.desiredWordCount?.max + 150) failures.push("article_outside_word_count_range");
  if (blockedPublicTerms.test(`${article.title} ${article.summary} ${article.body}`)) failures.push("internal_editorial_language_visible");
  if (blockedSalesTerms.test(`${article.title} ${article.summary} ${article.body}`)) failures.push("sales_cta_visible_in_news");
  if ((article.internalLinks || []).length > (site?.news?.maxInternalProductLinks || 1)) failures.push("too_many_internal_product_links");
  if (duplicateScore > 0.85) failures.push("semantic_duplicate_recent_publication");
  if ((article.informationGainScore || 0) < (site?.news?.minScore || 70)) failures.push("information_gain_below_threshold");
  return { eligible: failures.length === 0, failures: [...new Set(failures)], duplicateScore, wordCount };
}

async function recordRun(type, siteId, status, payload) {
  return saveCmsItem({
    type,
    siteId,
    slug: `${type}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    title: `${type} ${new Date().toISOString()}`,
    status,
    createdAt: new Date().toISOString(),
    ...payload
  });
}

export async function runNewsIngest({ siteId = DEFAULT_NEWS_SITE_ID, fallback = false, force = false, trigger = "cron" } = {}) {
  const site = getNewsSiteConfig(siteId);
  const validation = validateNewsSiteConfig(site);
  if (!validation.valid) return { success: false, status: "configuration_error", missing: validation.missing, siteId };
  if (!site.enabled || !site.news.enabled) return { success: true, status: "disabled", siteId };

  return withCmsAdvisoryLock(lockName(siteId, "ingest"), async () => {
    const state = await loadState(siteId);
    const lastRun = (await getCmsItems("news-ingest-run", { includeInactive: true, siteId }))[0];
    const elapsed = Date.now() - dateValue(lastRun?.createdAt);
    if (!force && elapsed > 0 && elapsed < site.news.ingestIntervalHours * 3600000) {
      return { success: true, status: "waiting_12_hours", siteId, nextRunAt: new Date(dateValue(lastRun.createdAt) + site.news.ingestIntervalHours * 3600000).toISOString() };
    }
    const discovery = await discoverNewsCandidates({ siteId, recentArticles: state.recent, fallback });
    const existingFingerprints = new Set(state.candidates.map((item) => item.sourceFingerprint).filter(Boolean));
    const accepted = discovery.candidates.filter((candidate) => !existingFingerprints.has(candidate.sourceFingerprint));
    for (const candidate of accepted) await saveCmsItem(candidate);
    const result = {
      success: true,
      status: "ingested",
      siteId,
      trigger,
      fallback,
      discovered: discovery.candidates.length,
      stored: accepted.length,
      rejected_sources: discovery.rejectedSources,
      errors: discovery.errors,
      source_groups: discovery.sourceGroups,
      nextRunAt: new Date(Date.now() + site.news.ingestIntervalHours * 3600000).toISOString()
    };
    await recordRun("news-ingest-run", siteId, "completed", result);
    console.log("[news-ingest]", JSON.stringify(result));
    return result;
  });
}

function selectCandidate(candidates, published) {
  const usedFingerprints = new Set(published.map((item) => item.sourceFingerprint).filter(Boolean));
  return candidates
    .filter((item) => ["candidate", "retry_pending", "reserved_for_cycle"].includes(item.status))
    .filter((item) => !usedFingerprints.has(item.sourceFingerprint))
    .sort((a, b) => b.informationGainScore - a.informationGainScore || dateValue(b.sourcePublishedAt) - dateValue(a.sourcePublishedAt))[0] || null;
}

async function verifyPublicDelivery(site, article, { baseUrl } = {}) {
  const origin = (baseUrl || process.env.PUBLIC_SITE_URL || site.siteUrl).replace(/\/$/, "");
  const listUrl = `${origin}${site.news.listRoute}`;
  const detailPath = site.news.detailRoutePattern.replace("[slug]", article.slug);
  const detailUrl = `${origin}${detailPath}`;
  const sitemapUrl = `${origin}${site.news.sitemapRoute}`;
  const checks = await Promise.allSettled([fetch(listUrl, { cache: "no-store" }), fetch(detailUrl, { cache: "no-store" }), fetch(sitemapUrl, { cache: "no-store" })]);
  const [list, detail, sitemap] = checks.map((entry) => entry.status === "fulfilled" ? entry.value : null);
  const [listText, detailText, sitemapText] = await Promise.all([list?.text() || "", detail?.text() || "", sitemap?.text() || ""]);
  const result = {
    listUrl, detailUrl, sitemapUrl,
    listStatus: list?.status || 0,
    detailStatus: detail?.status || 0,
    sitemapStatus: sitemap?.status || 0,
    listVisible: Boolean(list?.ok && (listText.includes(article.slug) || listText.includes(article.title))),
    detailVisible: Boolean(detail?.ok && detailText.includes(article.title) && detailText.includes(article.sourceUrl)),
    sitemapVisible: Boolean(sitemap?.ok && sitemapText.includes(article.slug)),
    checkedAt: new Date().toISOString()
  };
  result.success = result.listStatus === 200 && result.detailStatus === 200 && result.listVisible && result.detailVisible && (result.sitemapStatus !== 200 || result.sitemapVisible);
  return result;
}

export async function runNewsPublication({ siteId = DEFAULT_NEWS_SITE_ID, force = false, dryRun = false, baseUrl, trigger = "cron" } = {}) {
  const site = getNewsSiteConfig(siteId);
  const validation = validateNewsSiteConfig(site);
  if (!validation.valid) return { success: false, status: "configuration_error", missing: validation.missing, siteId };
  if (!site.enabled || !site.news.enabled || process.env.NEWS_AUTOPUBLISH_ENABLED !== "true") return { success: true, status: "disabled", siteId };

  return withCmsAdvisoryLock(lockName(siteId, "publish"), async () => {
    let state = await loadState(siteId);
    const latest = [...state.published].sort((a, b) => dateValue(b.publishedAt || b.createdAt) - dateValue(a.publishedAt || a.createdAt))[0];
    const nextEligibleAt = latest ? dateValue(latest.publishedAt || latest.createdAt) + site.news.publishIntervalHours * 3600000 : 0;
    if (!force && latest && Date.now() < nextEligibleAt) {
      return { success: true, status: "waiting_48_hours", siteId, nextRunAt: new Date(nextEligibleAt).toISOString() };
    }

    let candidate = selectCandidate(state.candidates, state.published);
    if (!candidate) {
      await runNewsIngest({ siteId, fallback: false, force: true, trigger: "publish-primary-fallback" });
      state = await loadState(siteId);
      candidate = selectCandidate(state.candidates, state.published);
    }
    if (!candidate) {
      await runNewsIngest({ siteId, fallback: true, force: true, trigger: "publish-fallback-whitelist" });
      state = await loadState(siteId);
      candidate = selectCandidate(state.candidates, state.published);
    }
    if (!candidate) {
      const result = { success: false, status: "no_compliant_candidate", siteId, trigger, published: 0 };
      await recordRun("news-publication-run", siteId, "retry_pending", result);
      return result;
    }

    await saveCmsItem({ ...candidate, status: "reserved_for_cycle", reservedAt: new Date().toISOString() });
    const composition = composeNewsArticle(candidate, { siteId });
    if (!composition.generated) {
      await saveCmsItem({ ...candidate, status: "rejected", rejectReason: composition.reason });
      return { success: false, status: "composition_rejected", reason: composition.reason, ...diagnostics(candidate) };
    }
    const article = composition.article;
    const quality = evaluateNewsArticle(article, state.recent, site);
    const audit = diagnostics(article, { word_count: quality.wordCount, trigger });
    if (!quality.eligible || dryRun) {
      await saveCmsItem({ ...candidate, status: quality.eligible ? "candidate" : "rejected", qualityFailures: quality.failures, ...audit });
      await recordRun("news-publication-run", siteId, quality.eligible ? "dry_run" : "rejected", { candidateSlug: candidate.slug, failures: quality.failures, ...audit });
      return { success: quality.eligible, status: quality.eligible ? "dry_run" : "candidate_rejected", published: 0, failures: quality.failures, ...audit };
    }

    const idempotencyKey = createHash("sha256").update(`${siteId}|${Math.floor(Date.now() / (site.news.publishIntervalHours * 3600000))}|${article.sourceFingerprint}`).digest("hex");
    if (state.published.some((item) => item.idempotencyKey === idempotencyKey || item.sourceFingerprint === article.sourceFingerprint)) {
      return { success: true, status: "duplicate_idempotency_key", published: 0, ...audit };
    }

    const publishedAt = new Date().toISOString();
    const publishedArticle = await saveCmsItem({ ...article, type: "news", status: "published", publishedAt, idempotencyKey, ...audit });
    revalidatePublishedNews(site, publishedArticle.slug);
    queueSitemapRefresh("news-published");
    const delivery = await verifyPublicDelivery(site, publishedArticle, { baseUrl });
    await recordRun("news-delivery-check", siteId, delivery.success ? "passed" : "retry_pending", { articleSlug: publishedArticle.slug, ...delivery });
    if (!delivery.success) {
      await saveCmsItem({ ...publishedArticle, type: "news", status: "offline", deliveryFailure: delivery, ...audit });
      await saveCmsItem({ ...candidate, status: "retry_pending", lastDeliveryFailure: delivery, ...audit });
      await recordRun("news-publication-run", siteId, "retry_pending", { candidateSlug: candidate.slug, delivery, ...audit });
      return { success: false, status: "frontend_verification_failed", published: 0, delivery, ...audit };
    }
    await saveCmsItem({ ...candidate, status: "used", usedAt: publishedAt, publishedArticleSlug: publishedArticle.slug, idempotencyKey, ...audit });
    await recordRun("news-publication-run", siteId, "published_success", { candidateSlug: candidate.slug, articleSlug: publishedArticle.slug, delivery, ...audit });
    return { success: true, status: "published_success", published: 1, slug: publishedArticle.slug, delivery, ...audit };
  });
}

// Compatibility for the previous route/import: it is no longer allowed to publish.
export async function runEditorialPublication(options = {}) {
  return runNewsIngest({ siteId: options.siteId || DEFAULT_NEWS_SITE_ID, force: options.force, trigger: "legacy-editorial-route" });
}
